"""质量过滤规则：每条规则既要拦住该拦的，也不能误杀正常文档。

阈值是在真实数据上校准的（docs/learn/p2-1-filters.md），这里用手写的小例子把关键行为固定下来。
"""

from __future__ import annotations

import pytest

from mytransformer.data import filters as F

EN = (
    "The water cycle describes how water moves between the land, the oceans and the atmosphere. "
    "Heat from the sun causes water to evaporate from lakes and seas, and the vapour rises until it "
    "cools and condenses into clouds. When the droplets become heavy enough they fall back to the "
    "ground as rain or snow, which then flows into rivers and eventually returns to the sea. "
    "Plants also play a part, because they release water through their leaves in a process called "
    "transpiration."
)
ZH = (
    "水循环是指水在陆地、海洋和大气之间不断运动的过程。太阳的热量使湖泊和海洋中的水蒸发，"
    "水蒸气上升到高空后遇冷凝结成云。云中的小水滴不断合并变大，最终以雨或雪的形式落回地面，"
    "再沿着河流汇入大海。植物同样参与其中，它们通过叶片把水分释放到空气里，这个过程叫做蒸腾作用。"
    "理解水循环有助于我们认识干旱与洪水的成因，也能帮助农民合理安排灌溉。"
)
ZH2 = (
    "城市的排水系统也和水循环密切相关。暴雨来临时，地面硬化面积越大，雨水越难渗入土壤，"
    "短时间内就会涌进管网，容易形成内涝。近年来不少地方开始建设透水铺装、下凹式绿地和雨水花园，"
    "让一部分雨水先留在原地慢慢下渗，既减轻了排水压力，又补充了地下水。"
)
CODE = '''import math


def area(radius: float) -> float:
    """Return the area of a circle."""
    return math.pi * radius ** 2


if __name__ == "__main__":
    print(area(2.0))
'''


# ---------------------------------------------------------------- 重复度的实现细节（照 datatrove）


def test_dup_ngram_skips_after_a_match():
    """找到重复就跳过这 n 个 token：a b c a b c a b c 里，后两组 "a b c" 各记一次，共 2×5 个字符。
    如果不跳过、每个位置都算，重叠的 "b c a"、"c a b" 也会被计入，结果偏大。"""
    toks = "a b c a b c a b c".split()
    assert F._dup_ngram_chars(toks, 3, " ") == 2 * len("a b c")


def test_repetition_divides_by_whole_text_length():
    """分母是整篇文本的字符数：加上大量空白，重复占比就被稀释。"""
    lines = "\n".join(["same line here"] * 3 + [f"unique line {i}" for i in range(7)])
    assert F.repetition(lines) is None                  # 2/10 行重复，按条数没超 30%
    heavy = "\n".join(["same line here"] * 5 + ["x"])
    assert F.repetition(heavy) == "重复行（按行数）"     # 4/6 行重复


# ---------------------------------------------------------------- 英文


def test_english_normal_text_passes():
    assert F.english(EN) is None


@pytest.mark.parametrize("text, reason", [
    ("Too short to be a real document.", "太短（< 50 词）"),
    (" ".join(["lorem"] * 60), "停用词不足"),
    ("\n".join(f"- item number {i} of the list" for i in range(60)), "几乎全是列表项"),
    (EN + (" click here to subscribe now" * 40), "最高频 2-gram 占比过高"),
])
def test_english_rejects(text, reason):
    assert F.english(text) == reason


# ---------------------------------------------------------------- 中文


def test_chinese_normal_text_passes():
    assert F.chinese(ZH) is None


def test_chinese_article_repeating_a_long_term_passes():
    """正常报道里一个 12 字的术语出现 6 次，不能当成重复。

    n×1 / n×2 / n×3 在真实数据上的丢弃率差别（22% / 6.0% / 3.8%）来自长文章里大量自然出现的短重复，
    手写的小例子复现不出来，由 scripts/calibrate_filters.py 在真实文档上测。
    """
    term = "新型冠状病毒感染肺炎疫情"
    text = (
        f"本市{term}防控工作持续推进，各社区按照要求落实排查措施。"
        f"专家提醒，{term}期间应减少聚集，出门佩戴口罩并勤洗手。"
        f"学校方面表示，{term}形势稳定后将逐步恢复线下教学安排。"
        f"交通部门介绍，受{term}影响，部分公交线路的班次有所调整。"
        f"医院开设专门通道，方便与{term}相关的就诊人员快速分流。"
        f"志愿者说，{term}以来社区邻里之间互相帮助的氛围更浓了。"
        + ZH + ZH2
    )
    assert F.chinese(text) is None


def test_chinese_rejects():
    assert F.chinese("你好。" * 10) == "太短（< 100 字）"
    refs = "\n".join(f"{i}. Smith, J. et al. (2015) Some Journal {i}, 825–834" for i in range(10))
    assert F.chinese("参考文献\n" + refs) == "汉字不到 40%"
    assert F.chinese(ZH + "\n" + ZH[:120] * 4) is not None  # 同一段话抄了好几遍


# ---------------------------------------------------------------- 代码


def test_code_normal_file_passes():
    assert F.code(CODE) is None


@pytest.mark.parametrize("text, reason", [
    ("var a=1;" * 200, "有超过 1000 字符的行（多半是压缩过的代码或数据）"),
    ("<!-- Generated by javadoc (version 1.7.0_51) -->\n" + CODE, "自动生成的文件"),
    ("x = 1\n", "太短"),
])
def test_code_rejects(text, reason):
    assert F.code(text) == reason


# ---------------------------------------------------------------- 数学 / 百科


def test_math_ignores_many_short_repeated_ui_lines():
    """论坛页：几十个 "Reply" 按条数超标，但只占全文很小一部分，数学内容本身是好的。"""
    body = "\n".join(f"Step {i}: substitute x = {i} into the equation and simplify both sides carefully."
                     for i in range(20))
    page = body + "\n" + "\n".join(["Reply"] * 30)
    assert F.FILTERS["math"](page) is None
    assert F.light(page, by_count=True) == "重复行（按行数）"


def test_every_subset_has_a_filter():
    """抽样脚本里的每个来源都要有对应的规则，否则管线跑到一半才报 KeyError。"""
    import importlib.util
    import sys
    from pathlib import Path

    path = Path(__file__).resolve().parents[1] / "scripts" / "sample_tokenizer_corpus.py"
    spec = importlib.util.spec_from_file_location("sample", path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod  # dataclass 需要能从 sys.modules 找到定义它的模块
    spec.loader.exec_module(mod)
    names = {s.name for s in mod.PARQUET_SOURCES} | {"en_web_dclm"}
    assert names == set(F.FILTERS)
